### ISSUE TITLE
WatermelonProblem Codeforces

### ISSUE THREAD

**Issue by aparna03dubey** [SanyaGera/Let-s-code-DSA#6]
One hot summer day Pete and his friend Billy decided to buy a watermelon. They chose the biggest and the ripest one, in their opinion. After that the watermelon was weighed, and the scales showed w kilos. They rushed home, dying of thirst, and decided to divide the berry, however they faced a hard problem.

Pete and Billy are great fans of even numbers, that's why they want to divide the watermelon in such a way that each of the two parts weighs even number of kilos, at the same time it is not obligatory that the parts are equal. The boys are extremely tired and want to start their meal as soon as possible, that's why you should help them and find out, if they can divide the watermelon in the way they want. For sure, each of them should get a part of positive weight.

Input
The first (and the only) input line contains integer number w (1 ≤ w ≤ 100) — the weight of the watermelon bought by the boys.

Output
Print YES, if the boys can divide the watermelon into two parts, each of them weighing even number of kilos; and NO in the opposite case.

**Comment by aparna03dubey** [comment]
Hey @SanyaGera 
Can you please assign this to me?

**Comment by SanyaGera** [comment]
Assigned

**Comment by AdiTyaa-Raj** [comment]
Hey admin, I wanted to complete this task. Can you assign this to me?
Thank you

**Comment by aparna03dubey** [comment]
Hey
Can you please check if it's what you are expecting?

**Comment by imdarshansingh** [comment]
hey admin can you assign me this project . I'll provide you the fresh and clear code with comments on each line .
